2023-04-12 17:02:30.834 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} Look at the properties
2023-04-12 17:02:30.937 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} They're still here
2023-04-12 17:02:30.938 +03:00 [INF]{"SourceContext":"ConsumerConsoleApp.Services.KafkaConsumer"} I have a parameter with my class name!
2023-04-12 17:02:31.547 +03:00 [DBG]{} Hi, this is a debug string. wow
2023-04-12 17:02:31.548 +03:00 [ERR]{} Error! I have logged an error!
2023-04-12 17:02:31.584 +03:00 [WRN]{} I'm about to create an exception!
2023-04-12 17:02:31.624 +03:00 [FTL]{} Debugging an exception what ProducerConsoleApp.Models.Bet, {"Id":0,"GameId":0,"UserId":0,"StakeAmount":69,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}
System.Exception: Big Exception happened
   at ConsumerConsoleApp.Services.ExceptionThrower.DoIt() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\ExceptionThrower.cs:line 14
   at ConsumerConsoleApp.Services.KafkaConsumer.StartConsuming() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\KafkaConsumer.cs:line 22
2023-04-12 17:46:09.068 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} Look at the properties
2023-04-12 17:46:09.101 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} They're still here
2023-04-12 17:46:09.102 +03:00 [INF]{"SourceContext":"ConsumerConsoleApp.Services.KafkaConsumer"} I have a parameter with my class name!
2023-04-12 17:46:09.145 +03:00 [DBG]{} Hi, this is a debug string. wow
2023-04-12 17:46:09.145 +03:00 [ERR]{} Error! I have logged an error!
2023-04-12 17:46:09.154 +03:00 [WRN]{} I'm about to create an exception!
2023-04-12 17:46:09.171 +03:00 [FTL]{} Debugging an exception what ProducerConsoleApp.Models.Bet, {"Id":0,"GameId":0,"UserId":0,"StakeAmount":69,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}
System.Exception: Big Exception happened
   at ConsumerConsoleApp.Services.ExceptionThrower.DoIt() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\ExceptionThrower.cs:line 14
   at ConsumerConsoleApp.Services.KafkaConsumer.StartConsuming() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\KafkaConsumer.cs:line 22
2023-04-12 17:46:32.051 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} Look at the properties
2023-04-12 17:46:32.086 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} They're still here
2023-04-12 17:46:32.087 +03:00 [INF]{"SourceContext":"ConsumerConsoleApp.Services.KafkaConsumer"} I have a parameter with my class name!
2023-04-12 17:46:32.125 +03:00 [DBG]{} Hi, this is a debug string. wow
2023-04-12 17:46:32.125 +03:00 [ERR]{} Error! I have logged an error!
2023-04-12 17:46:32.264 +03:00 [WRN]{} I'm about to create an exception!
2023-04-12 17:46:32.299 +03:00 [FTL]{} Debugging an exception what ProducerConsoleApp.Models.Bet, {"Id":0,"GameId":0,"UserId":0,"StakeAmount":69,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}
System.Exception: Big Exception happened
   at ConsumerConsoleApp.Services.ExceptionThrower.DoIt() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\ExceptionThrower.cs:line 14
   at ConsumerConsoleApp.Services.KafkaConsumer.StartConsuming() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\KafkaConsumer.cs:line 22
2023-04-12 17:47:05.901 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} Look at the properties
2023-04-12 17:47:05.937 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} They're still here
2023-04-12 17:47:05.938 +03:00 [INF]{"SourceContext":"ConsumerConsoleApp.Services.KafkaConsumer"} I have a parameter with my class name!
2023-04-12 17:47:06.054 +03:00 [DBG]{} Hi, this is a debug string. wow
2023-04-12 17:47:06.054 +03:00 [ERR]{} Error! I have logged an error!
2023-04-12 17:47:06.164 +03:00 [WRN]{} I'm about to create an exception!
2023-04-12 17:47:06.197 +03:00 [FTL]{} Debugging an exception what ProducerConsoleApp.Models.Bet, {"Id":0,"GameId":0,"UserId":0,"StakeAmount":69,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}
System.Exception: Big Exception happened
   at ConsumerConsoleApp.Services.ExceptionThrower.DoIt() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\ExceptionThrower.cs:line 14
   at ConsumerConsoleApp.Services.KafkaConsumer.StartConsuming() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\KafkaConsumer.cs:line 22
2023-04-12 17:50:10.223 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} Look at the properties
2023-04-12 17:50:10.272 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} They're still here
2023-04-12 17:50:10.273 +03:00 [INF]{"SourceContext":"ConsumerConsoleApp.Services.KafkaConsumer"} I have a parameter with my class name!
2023-04-12 17:50:10.322 +03:00 [DBG]{} Hi, this is a debug string. wow
2023-04-12 17:50:10.322 +03:00 [ERR]{} Error! I have logged an error!
2023-04-12 17:50:10.452 +03:00 [WRN]{} I'm about to create an exception!
2023-04-12 17:50:10.487 +03:00 [FTL]{} Debugging an exception what ProducerConsoleApp.Models.Bet, {"Id":0,"GameId":0,"UserId":0,"StakeAmount":69,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}
System.Exception: Big Exception happened
   at ConsumerConsoleApp.Services.ExceptionThrower.DoIt() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\ExceptionThrower.cs:line 14
   at ConsumerConsoleApp.Services.KafkaConsumer.StartConsuming() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\KafkaConsumer.cs:line 22
2023-04-12 17:54:39.655 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} Look at the properties
2023-04-12 17:54:39.683 +03:00 [INF]{"MyContextName":{"Id":0,"GameId":0,"UserId":0,"StakeAmount":123,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}} They're still here
2023-04-12 17:54:39.683 +03:00 [INF]{"SourceContext":"ConsumerConsoleApp.Services.KafkaConsumer"} I have a parameter with my class name!
2023-04-12 17:54:39.689 +03:00 [DBG]{} Hi, this is a debug string. wow
2023-04-12 17:54:39.689 +03:00 [ERR]{} Error! I have logged an error!
2023-04-12 17:54:39.750 +03:00 [WRN]{} I'm about to create an exception!
2023-04-12 17:54:39.768 +03:00 [FTL]{} Debugging an exception what ProducerConsoleApp.Models.Bet, {"Id":0,"GameId":0,"UserId":0,"StakeAmount":69,"WinAmount":null,"Created":"0001-01-01T00:00:00.0000000","$type":"Bet"}
System.Exception: Big Exception happened
   at ConsumerConsoleApp.Services.ExceptionThrower.DoIt() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\ExceptionThrower.cs:line 14
   at ConsumerConsoleApp.Services.KafkaConsumer.StartConsuming() in C:\Users\Jox\source\repos\TestConsoleAppNET\ConsumerConsoleApp\Services\KafkaConsumer.cs:line 22
